polizei:
  approvals: 3
  title_must_contain: POL-
  title_must_not_contain: WIP | wip
  title_must_be_prefixed: POL-
  title_must_be_suffixed: null
  commits_must_be_prefixed: POL-
  commits_must_be_suffixed: null
  validate_label_population:
    enabled:  true
    message: "Please add >= 1 issue label to better organize repo issues."

